In [38]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.model_selection import train_test_split

In [39]:
data={
    'Age':[25,30,28,35,40],
    'Salary':[25000,40000,35000,60000,70000],
    'Department':['HR','IT','Finance','IT','HR'],
    'Experince':[1,5,3,8,12],
    'Attrition':['No','Yes','No','Yes','No']

}

In [40]:
df=pd.DataFrame(data)

In [41]:
df.head()

   Age  Salary Department  Experince Attrition
0   25   25000         HR          1        No
1   30   40000         IT          5       Yes
2   28   35000    Finance          3        No
3   35   60000         IT          8       Yes
4   40   70000         HR         12        No

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Age         5 non-null      int64
 1   Salary      5 non-null      int64
 2   Department  5 non-null      object
 3   Experince   5 non-null      int64
 4   Attrition   5 non-null      object
dtypes: int64(3), object(2)
memory usage: 332.0+ bytes

In [43]:
df.dtypes

Age            int64
Salary         int64
Department    object
Experince      int64
Attrition     object
dtype: object

In [44]:
df.columns

Index(['Age', 'Salary', 'Department', 'Experince', 'Attrition'], dtype='object')

In [45]:
df.describe()

            Age        Salary  Experince
count   5.00000      5.000000    5.00000
mean   31.60000  46000.000000    5.80000
std     5.94138  18506.755523    4.32435
min    25.00000  25000.000000    1.00000
25%    28.00000  35000.000000    3.00000
50%    30.00000  40000.000000    5.00000
75%    35.00000  60000.000000    8.00000
max    40.00000  70000.000000   12.00000

In [46]:
df.isnull().sum()

Age           0
Salary        0
Department    0
Experince     0
Attrition     0
dtype: int64

In [47]:
le=LabelEncoder()

In [48]:
df['Department']=le.fit_transform(df['Department'])
df['Attrition']=le.fit_transform(df['Attrition'])

In [49]:
print("after encodind")
df

after encodind

   Age  Salary  Department  Experince  Attrition
0   25   25000           1          1          0
1   30   40000           2          5          1
2   28   35000           0          3          0
3   35   60000           2          8          1
4   40   70000           1         12          0

In [50]:
x=df.drop('Attrition',axis=1)
y=df['Attrition']

In [52]:
X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42)

In [53]:
scaler = StandardScaler()

In [55]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)