In [47]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

In [3]:
df=pd.read_csv("/content/customer_dataset_.csv")

In [4]:
df.head()

   Customer_ID   Age  Gender     City   Salary  Spending_Score Purchased
0          101  35.0    Male  Calicut  42366.0           100.0        No
1          102  57.0  Female    Kochi  73362.0            78.0        No
2          103  40.0  Female  Calicut  18664.0            33.0       Yes
3          104  48.0    Male    Kochi  78043.0            98.0       Yes
4          105  38.0    Male  Calicut  54369.0            50.0       Yes

In [11]:
df.shape

(100, 7)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Customer_ID     100 non-null    int64
 1   Age             99 non-null     float64
 2   Gender          99 non-null     object
 3   City            99 non-null     object
 4   Salary          98 non-null     object
 5   Spending_Score  99 non-null     float64
 6   Purchased       100 non-null    object
dtypes: float64(2), int64(1), object(4)
memory usage: 5.6+ KB

In [6]:
df.columns

Index(['Customer_ID', 'Age', 'Gender', 'City', 'Salary', 'Spending_Score',
       'Purchased'],
      dtype='object')

In [7]:
df.dtypes

Customer_ID         int64
Age               float64
Gender             object
City               object
Salary             object
Spending_Score    float64
Purchased          object
dtype: object

In [8]:
df.duplicated().sum()

np.int64(1)

In [9]:
df.isnull().sum()

Customer_ID       0
Age               1
Gender            1
City              1
Salary            2
Spending_Score    1
Purchased         0
dtype: int64

In [19]:
print("Before preprocessing")
print("Gender:", df["Gender"].unique())
print("City:", df["City"].unique())
print("Purchased:", df["Purchased"].unique())

Before preprocessing
Gender: ['Male' 'Female' nan]
City: ['Calicut' 'Kochi' 'Trivandrum' 'Kottayam' nan]
Purchased: ['No' 'Yes']

In [12]:
# Remove unwanted spaces
df["Gender"] = df["Gender"].str.strip()
df["City"] = df["City"].str.strip()
df["Purchased"] = df["Purchased"].str.strip()

In [13]:
# Standardize capitalization
df["Gender"] = df["Gender"].str.title()
df["City"] = df["City"].str.title()
df["Purchased"] = df["Purchased"].str.title()

In [14]:
print("Gender values:")
print(df["Gender"].value_counts())

Gender values:
Gender
Female    51
Male      48
Name: count, dtype: int64

In [15]:
print("\nCity values:")
print(df["City"].value_counts())

City values:
City
Trivandrum    27
Kottayam      25
Kochi         24
Calicut       23
Name: count, dtype: int64

In [16]:
print("\nPurchased values:")
print(df["Purchased"].value_counts())

Purchased values:
Purchased
Yes    57
No     43
Name: count, dtype: int64

In [18]:
print("Gender:", df["Gender"].unique())
print("City:", df["City"].unique())
print("Purchased:", df["Purchased"].unique())

Gender: ['Male' 'Female' nan]
City: ['Calicut' 'Kochi' 'Trivandrum' 'Kottayam' nan]
Purchased: ['No' 'Yes']

In [21]:
df.dtypes

Customer_ID         int64
Age               float64
Gender             object
City               object
Salary             object
Spending_Score    float64
Purchased          object
dtype: object

In [22]:

df["Age"] = pd.to_numeric(df["Age"], errors="coerce")

In [23]:

df["Salary"] = pd.to_numeric(df["Salary"], errors="coerce")

In [24]:

print(df.dtypes)

Customer_ID         int64
Age               float64
Gender             object
City               object
Salary            float64
Spending_Score    float64
Purchased          object
dtype: object

In [26]:
df['Age'].head()

0    35.0
1    57.0
2    40.0
3    48.0
4    38.0
Name: Age, dtype: float64

In [27]:
# Check missing values created by conversion
print("\nMissing values:")
print(df.isnull().sum())

Missing values:
Customer_ID       0
Age               1
Gender            1
City              1
Salary            3
Spending_Score    1
Purchased         0
dtype: int64

In [28]:
print("Duplicates before cleaning:", df.duplicated().sum())

Duplicates before cleaning: 1

In [30]:
df = df.drop_duplicates()

In [31]:
print("Duplicates after cleaning:", df.duplicated().sum())

Duplicates after cleaning: 0

In [32]:
print(len(df))

99

In [33]:
print(df.isnull().sum())

Customer_ID       0
Age               1
Gender            1
City              1
Salary            3
Spending_Score    1
Purchased         0
dtype: int64

In [36]:
df["Age"] = df["Age"].fillna(df["Age"].median())

df["Salary"] = df["Salary"].fillna(df["Salary"].median())

df["Spending_Score"] = df["Spending_Score"].fillna(df["Spending_Score"].median())

/tmp/ipykernel_1037/2774769380.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age"] = df["Age"].fillna(df["Age"].median())
/tmp/ipykernel_1037/2774769380.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Salary"] = df["Salary"].fillna(df["Salary"].median())
/tmp/ipykernel_1037/2774769380.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Spending_Score"] = df["Spending_Score"].fillna(df["Spending_Score"].median())

In [35]:
df["Gender"] = df["Gender"].fillna(df["Gender"].mode()[0])

df["City"] = df["City"].fillna(df["City"].mode()[0])

/tmp/ipykernel_1037/1921037737.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Gender"] = df["Gender"].fillna(df["Gender"].mode()[0])
/tmp/ipykernel_1037/1921037737.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["City"] = df["City"].fillna(df["City"].mode()[0])

In [37]:
print("Missing values after filling:")
print(df.isnull().sum())

Missing values after filling:
Customer_ID       0
Age               0
Gender            0
City              0
Salary            0
Spending_Score    0
Purchased         0
dtype: int64

In [38]:
num_cols = ["Age", "Salary", "Spending_Score"]

In [39]:
for col in num_cols:

    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[
        (df[col] < lower) | (df[col] > upper)
    ]

In [43]:
print("\nColumn:", col)
print("Lower limit:", lower)
print("Upper limit:", upper)
print("Number of outliers:", len(outliers))
print(outliers[["Customer_ID", col]])

Column: Spending_Score
Lower limit: -53.75
Upper limit: 156.25
Number of outliers: 1
    Customer_ID  Spending_Score
78          179           250.0

In [44]:
for col in num_cols:

    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    df[col] = df[col].clip(lower, upper)

print("Outlier capping completed.")

Outlier capping completed.

/tmp/ipykernel_1037/4054307493.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].clip(lower, upper)
/tmp/ipykernel_1037/4054307493.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].clip(lower, upper)
/tmp/ipykernel_1037/4054307493.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].clip(lower, upper)

In [45]:
print(df[["Age", "Salary", "Spending_Score"]].describe())

             Age         Salary  Spending_Score
count  99.000000      99.000000       99.000000
mean   39.641414   51003.070707       52.093434
std    11.645495   21763.572615       31.871585
min    20.000000   18355.000000        1.000000
25%    30.500000   33196.500000       25.000000
50%    39.000000   47986.500000       51.000000
75%    48.500000   68828.500000       77.500000
max    75.500000  122276.500000      156.250000

In [46]:
df = pd.get_dummies(df, columns=["Gender", "City"], drop_first=True, dtype=int)

df.head()

,Customer_ID,Age,Salary,Spending_Score,Purchased,Gender_Male,City_Kochi,City_Kottayam,City_Trivandrum
0,101,35.0,42366.0,100.0,No,1,0,0,0
1,102,57.0,73362.0,78.0,No,0,1,0,0
2,103,40.0,18664.0,33.0,Yes,0,0,0,0
3,104,48.0,78043.0,98.0,Yes,1,1,0,0
4,105,38.0,54369.0,50.0,Yes,1,0,0,0

In [48]:
num_cols = ["Age", "Salary", "Spending_Score"]

scaler = StandardScaler()

df[num_cols] = scaler.fit_transform(df[num_cols])

df.head()

,Customer_ID,Age,Salary,Spending_Score,Purchased,Gender_Male,City_Kochi,City_Kottayam,City_Trivandrum
0,101,-0.400587,-0.398879,1.510762,No,1,0,0,0
1,102,1.498169,1.032584,0.816979,No,0,1,0,0
2,103,0.030949,-1.493489,-0.602123,Yes,0,0,0,0
3,104,0.721405,1.248763,1.447690,Yes,1,1,0,0
4,105,-0.141666,0.155446,-0.066018,Yes,1,0,0,0

In [49]:
# Convert Purchased column into numbers
df["Purchased"] = df["Purchased"].map({"No": 0, "Yes": 1})

In [50]:
# Separate features (X) and target (y)
X = df.drop(columns=["Customer_ID", "Purchased"])
y = df["Purchased"]

In [52]:
print("Features (X):")
X.head()

Features (X):

,Age,Salary,Spending_Score,Gender_Male,City_Kochi,City_Kottayam,City_Trivandrum
0,-0.400587,-0.398879,1.510762,1,0,0,0
1,1.498169,1.032584,0.816979,0,1,0,0
2,0.030949,-1.493489,-0.602123,0,0,0,0
3,0.721405,1.248763,1.447690,1,1,0,0
4,-0.141666,0.155446,-0.066018,1,0,0,0

In [53]:
print("\nTarget (y):")
y.head()

Target (y):

0    0
1    0
2    1
3    1
4    1
Name: Purchased, dtype: int64

In [54]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("Training features:", X_train.shape)
print("Testing features:", X_test.shape)

print("Training target:", y_train.shape)
print("Testing target:", y_test.shape)

Training features: (79, 7)
Testing features: (20, 7)
Training target: (79,)
Testing target: (20,)

In [55]:
df.to_csv("cleaned_customer_dataset.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [56]:
from google.colab import files

files.download("cleaned_customer_dataset.csv")